Introduce new volume type and objectstorage endpoint
syseleven/grav-docs-syseleven-stack pull request #231
Opened 2022-12-22 09:46 UTC by lgrebe-sys

os-13135

2022-12-23 16:39 UTC, matthiasbernhardt commented on user/pages/04.Reference/05.object-storage/docs.en.md
> +website hosting configuration    | no                            | no                            |
CORS is part of this, we should group them and clarify what exactly, if not everything from this category, is supported.

2023-01-09 16:07 UTC, bpetermannS11 requested changes

2023-01-09 16:07 UTC, bpetermannS11 commented on user/pages/04.Reference/05.object-storage/docs.en.md
> +
too many blank lines

2023-01-09 16:07 UTC, bpetermannS11 commented on user/pages/04.Reference/05.object-storage/docs.en.md
> +
too many blank lines

2023-01-09 16:07 UTC, bpetermannS11 commented on user/pages/04.Reference/04.block-storage/docs.en.md
> +
too many blank lines

2023-01-09 16:14 UTC, bpetermannS11 requested changes

2023-01-09 16:14 UTC, bpetermannS11 commented on user/pages/04.Reference/05.object-storage/docs.en.md
> +bucket/object ACL                | partially*                    | partially*                    |
The (*) doesn't appear below the table

2023-01-10 12:15 UTC, bpetermannS11 requested changes

2023-01-10 12:15 UTC, bpetermannS11 commented on user/pages/04.Reference/04.block-storage/docs.en.md
> +The volumes can only be attached to a single virtual machine at a time.
```suggestion
A volume can only be attached to a single virtual machine at a time.
```

2023-01-11 10:25 UTC, matthiasbernhardt commented on user/pages/04.Reference/04.block-storage/docs.en.md
> +A volume can only be attached to a single virtual machine at a time.
Keep in sync with L29/30

2023-01-11 10:27 UTC, matthiasbernhardt commented on user/pages/04.Reference/05.object-storage/docs.en.md
> +CORS                             | no                            | yes                           |
shall we write a bit more verbosely "- setting CORS headers" here?

2023-01-17 14:51 UTC, lgrebe-sys commented on user/pages/04.Reference/04.block-storage/docs.en.md
> +A volume can only be attached to a single virtual machine at a time.
Lines are in sync again =)

2023-01-19 09:06 UTC, cornuwel submitted a review, later dismissed

2023-06-14 10:36 UTC, MortezaBashsiz approved these changes
I have reviewed and seems good from my point of view

2023-06-30 09:46 UTC, MortezaBashsiz approved these changes
Its fine from my side
Approved

2023-07-03 09:58 UTC, matthiasbernhardt approved these changes

2023-07-03 12:06 UTC, bpetermannS11 approved these changes

2023-07-03 12:35 UTC, merged